[project]
name = "svc1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Shawn Oster", email = "shawn.oster@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "core",
]

[project.scripts]
svc1 = "svc1:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
core = { workspace = true }
