[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "plugin-one"
readme = "README.md"
description = "Plugin One Plugin"
maintainers = [{"name" = "fitness-function-maintainers"}]
keywords = ["sqa-developer-productivity"]
version = "0.5.1"
requires-python = ">=3.12"
dependencies = ["sqa-api"]

[project.entry-points."sqa.plugins"]
plugin-one = "plugin_one.plugin_one_plugin:PluginOnePlugin"

[tool.uv.sources]
sqa-api = { workspace = true }

[tool.semantic_release]
build_command = "pip install uv && uv build -v -o ./dist"
commit_message = "chore(plugin-one-release): release plugin_one@{version} [skip ci]"
commit_parser = "../../scripts/psr/custom_parser/monorepo_parser.py:ConventionalCommitMonorepoParser"
tag_format = "plugin-one-v{version}"
version_toml = ["pyproject.toml:project.version"]
version_variables = ["plugin_one/__init__.py:__version__"]

# Branch settings: define which branches do releases
[tool.semantic_release.branches.main]
match = "main"

[tool.semantic_release.publish]
dist_glob_patterns = ["../../dist/plugin_one*"]