[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sqa-api"
version = "0.5.1"
description = "Shared plugin interface for SQA CLI and plugins"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = []

[tool.semantic_release]
build_command = "pip install --root-user-action=ignore uv && uv build"
commit_message = "chore(sqa-api-release): release sqa-api@{version} [skip ci]"
commit_parser = "../scripts/psr/custom_parser/monorepo_parser.py:ConventionalCommitMonorepoParser"
dist_glob_patterns = ["./dist/*.whl", "./dist/*.tar.gz"]
tag_format = "sqa-api-v{version}"
version_toml = ["pyproject.toml:project.version"]
version_variables = ["sqa_api/__init__.py:__version__"]

[semantic_release.branches.main]
match = "main"

[tool.semantic_release.publish]
dist_glob_patterns = ["dist/sqa_api*.*"]
