[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sqa-api"
version = "0.4.6"
description = "Shared plugin interface for SQA CLI and plugins"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = []

[tool.semantic_release]
build_command = "pip install uv && uv build"
tag_format = "sqa-api-v{version}"
version_toml = ["pyproject.toml:project.version"]
version_variables = ["sqa_api/__init__.py:__version__"]
commit_message = "chore(sqa-api-release): release sqa-api@{version} [skip ci]"
dist_glob_patterns = ["dist/*.whl", "dist/*.tar.gz"]

[semantic_release.branches.main]
match = "main"

[tool.semantic_release.changelog]
exclude_commit_patterns = [
  "chores*"
]
changelog_sections = [
  "feat",
  "fix",
  "perf",
  "refactor"
]
