name: Reusable Release Action
on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
    secrets:
      github_release_token:
        required: true

jobs:
  release-package:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-release-${{ inputs.package }}-${{ github.ref_name }}
      cancel-in-progress: false

    permissions:
      contents: write    # allow pushing tags and creating releases

    steps:
      - name: Setup | Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Setup | Sync with upstream branch
        run: |
          git fetch origin ${{ github.ref_name }}
          git pull origin ${{ github.ref_name }} --rebase

      - name: Action | Semantic Version Release (${{ inputs.package }} package)
        id: release_package
        uses: python-semantic-release/python-semantic-release@v9
        with:
          directory: ./${{ inputs.package }}
          github_token: ${{ secrets.github_release_token }}
          git_committer_name: "github-actions"
          git_committer_email: "actions@users.noreply.github.com"

      - name: Publish | Upload to GitHub Release Assets (${{ inputs.package }} package)
        uses: python-semantic-release/publish-action@v9.21.0
        if: steps.release_package.outputs.released == 'true'
        with:
          tag: ${{ steps.release_package.outputs.tag }}
          github_token: ${{ secrets.github_release_token }}
