name: Reusable Release Action
on:
  workflow_call:
    inputs:
      directory:
        required: true
        type: string
    secrets:
      github_token:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release Package
        id: release-package
        uses: python-semantic-release/python-semantic-release@v9
        with:
          directory: ${{ inputs.directory }}
          github_token: ${{ secrets.github_token }}

      - name: Publish Artifacts to GitHub Release
        if: steps.release-package.outputs.released == 'true'
        uses: python-semantic-release/publish-action@v9.21.0
        with:
          tag: ${{ steps.release-package.outputs.tag }}
          github_token: ${{ secrets.github_token }}
